# STAGE 1: Run tests
FROM golang:1.17.6-alpine3.15 as test
RUN apk add --no-cache gcc musl-dev make yarn
ADD ./woodpecker /woodpecker

ENV GOOS=linux
WORKDIR /woodpecker
RUN make test
RUN make test-frontend

# STAGE 2: build
FROM test AS build
# ARG VERSION
ENV GOOS=linux CGO_ENABLED=0 
RUN make build-server
