FROM alpine:latest
ARG VERSION="unknown"

ENV DATABASE_DRIVER sqlite3
ENV DATABASE_CONFIG /var/lib/drone/drone.sqlite
ENV GODEBUG netdns=go
ENV XDG_CACHE_HOME /var/lib/drone
ENV WOODPECKER_VERSION ${VERSION}

COPY --from=localhost:5000/woodpecker/build /woodpecker/release/drone-server /bin/

EXPOSE 8000 9000 80 443

CMD ["/bin/drone-server"]
