FROM alpine:latest
EXPOSE 8000 9000 80 443

ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite
ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME /var/lib/drone

COPY --from=woodpecker-build /woodpecker/release/drone-server /bin/

CMD ["/bin/drone-server"]
