# STAGE 3: assemble final image
FROM alpine:latest
ARG VERSION="unknown"

ENV GODEBUG netdns=go
ENV WOODPECKER_VERSION ${VERSION}

RUN apk add -U --no-cache ca-certificates
COPY --from=localhost:5000/woodpecker/build /woodpecker/dist/woodpecker-agent /bin/woodpecker-agent
RUN ln -s /bin/woodpecker-agent /bin/agent
RUN ln -s /bin/woodpecker-agent /bin/drone-agent

EXPOSE 3000
HEALTHCHECK CMD ["/bin/agent", "ping"]

CMD ["/bin/agent"]
