name: Build latest tag

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
  WOODPECKER_BUILD_AGENT: true
  WOODPECKER_BUILD_SERVER: true

jobs:

  build-images:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to DockerHub
        if: env.PUSH_IMAGE
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: env.PUSH_IMAGE
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get latest Woodpecker tag
        run: |
          cd woodpecker
          git fetch --tags
          LATEST_TAG_REV=$(git rev-list --tags --max-count 1)
          WOODPECKER_VERSION=$(git describe --tags ${LATEST_TAG_REV})
          echo "WOODPECKER_VERSION=${WOODPECKER_VERSION}" >> $GITHUB_ENV
          git checkout ${WOODPECKER_VERSION}

      - name: Check whether latest release needs building
        if: ${{ env.PUSH_IMAGE }}
        run: |
          # Assume we're going to build both server and agent unless the images already exist.
          echo "WOODPECKER_BUILD_SERVER=true" >> $GITHUB_ENV
          echo "WOODPECKER_BUILD_AGENT=true" >> $GITHUB_ENV

          # Check whether we can skip building the server
          SERVER_TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/${{ secrets.DOCKERHUB_USERNAME }}/woodpecker-server/tags | jq -r ".[].name")
          for tag in ${SERVER_TAGS[@]}; do
            if [[ "$tag" == "${WOODPECKER_VERSION}" ]]; then
              echo "Server ${tag} has already been built."
              echo "WOODPECKER_BUILD_SERVER=false" >> $GITHUB_ENV
              break
            fi
          done

          # Check whether we can skip building the agent
          AGENT_TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/${{ secrets.DOCKERHUB_USERNAME }}/woodpecker-agent/tags | jq -r ".[].name")
          for tag in ${AGENT_TAGS[@]}; do
            if [[ "$tag" == "${WOODPECKER_VERSION}" ]]; then
              echo "Agent ${tag} has already been built."
              echo "WOODPECKER_BUILD_AGENT=false" >> $GITHUB_ENV
              break
            fi
          done

      - name: Docker Setup QEMU
        if: ${{ env.WOODPECKER_BUILD_SERVER || env.WOODPECKER_BUILD_AGENT }}
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        if: ${{ env.WOODPECKER_BUILD_SERVER || env.WOODPECKER_BUILD_AGENT }}
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build Woodpecker
        if: ${{ env.WOODPECKER_BUILD_SERVER || env.WOODPECKER_BUILD_AGENT }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.build
          tags: localhost:5000/woodpecker/build
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}

      - name: Build Woodpecker Server image
        if: ${{ env.WOODPECKER_BUILD_SERVER }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.server
          tags: |
            ghcr.io/${{ github.repository_owner }}/woodpecker-server:${{ env.WOODPECKER_VERSION }}
            florianpiesche/woodpecker-server:${{ env.WOODPECKER_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}

      - name: Build Woodpecker Agent image
        if: ${{ env.WOODPECKER_BUILD_AGENT }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.agent
          tags: |
            ghcr.io/${{ github.repository_owner }}/woodpecker-agent:${{ env.WOODPECKER_VERSION }}
            florianpiesche/woodpecker-agent:${{ env.WOODPECKER_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}
