name: Build dev image

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:
  
env:
  PLATFORMS: linux/arm64/v8,linux/amd64
  # PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}

jobs:

  build-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current commit on woodpecker submodule
        run: |
          echo WOODPECKER_COMMIT=$(git rev-parse --short @:./woodpecker) >> $GITHUB_ENV

      - name: Build Woodpecker
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.build
          tags: localhost:5000/woodpecker/build
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_COMMIT }}

      - name: Build Woodpecker Server image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.server
          tags: |
            ghcr.io/${{ github.repository_owner }}/woodpecker-server:dev
            ghcr.io/${{ github.repository_owner }}/woodpecker-server:${{ env.WOODPECKER_COMMIT }}
            florianpiesche/woodpecker-server:dev
            florianpiesche/woodpecker-server:${{ env.WOODPECKER_COMMIT }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
          build-args: VERSION=${{ env.WOODPECKER_COMMIT }}

      # - name: Build Woodpecker Agent image
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: Dockerfile.agent
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/woodpecker-agent:latest
      #       ghcr.io/${{ github.repository_owner }}/woodpecker-agent:${{ env.WOODPECKER_COMMIT }}
      #       florianpiesche/woodpecker-agent:latest
      #       florianpiesche/woodpecker-agent:${{ env.WOODPECKER_COMMIT }}
      #     platforms: ${{ env.PLATFORMS }}
      #     push: ${{ env.PUSH_IMAGE }}
      #     build-args: VERSION=${{ env.WOODPECKER_COMMIT }}
