name: Build dev image

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:

  build-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current Woodpecker revision ID
        run: |
          cd woodpecker
          echo "WOODPECKER_VERSION=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3
        with:
          driver-opts: network=host

      - name: Build Woodpecker
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.build
          tags: localhost:5000/woodpecker/build
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}

      - name: Build and push Woodpecker Server image
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.server
          tags: |
            florianpiesche/woodpecker-server:dev
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}

      - name: Build and push Woodpecker Agent image
        if: env.WOODPECKER_BUILD_AGENT == 'true'
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.agent
          tags: |
            florianpiesche/woodpecker-agent:dev
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}
