name: Build latest tag

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:

  build-image:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Woodpecker tag
        run: |
          cd woodpecker
          git fetch --tags
          LATEST_TAG_REV=$(git rev-list --tags --max-count 1)
          WOODPECKER_VERSION=$(git describe --tags ${LATEST_TAG_REV})
          echo "WOODPECKER_VERSION=${WOODPECKER_VERSION}" >> $GITHUB_ENV
          git checkout ${WOODPECKER_VERSION}

      - name: Check whether latest release needs building
        run: |
          TAGS=$(curl -s https://registry.hub.docker.com/v1/repositories/florianpiesche/woodpecker-server/tags | jq -r ".[].name")

          for tag in ${TAGS[@]}; do
            if [[ "$tag" == "${WOODPECKER_VERSION}" ]]; then
              echo "WOODPECKER_BUILD_TAG=false" >> $GITHUB_ENV
              exit 0
            fi
          done

          echo "WOODPECKER_BUILD_TAG=true" >> $GITHUB_ENV

      - name: Docker Setup QEMU
        if: env.WOODPECKER_BUILD_TAG == 'true'
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        if: env.WOODPECKER_BUILD_TAG == 'true'
        uses: docker/setup-buildx-action@v1.0.3
        with:
          driver-opts: network=host

      - name: Build Woodpecker
        if: env.WOODPECKER_BUILD_TAG == 'true'
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.build
          tags: localhost:5000/woodpecker/build
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: VERSION=${{ env.WOODPECKER_VERSION }}

      - name: Build and push Woodpecker Server image
        if: env.WOODPECKER_BUILD_TAG == 'true'
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.server
          tags: |
            florianpiesche/woodpecker-server:latest
            florianpiesche/woodpecker-server:${{ env.WOODPECKER_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: true

      - name: Build and push Woodpecker Agent image
        if: env.WOODPECKER_BUILD_TAG == 'true'
        uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile.agent
          tags: |
            florianpiesche/woodpecker-agent:latest
            florianpiesche/woodpecker-agent:${{ env.WOODPECKER_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: true
